[build]
  functions = "netlify/functions"
[functions]
  included_files = ["backend/routes/*"]
  external_node_modules = ["express", "serverless-http"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
[[redirects]]
  from = "/*"
  to = "index.html"
  status = 200