export default {
  'Deletee (Intro)': { a: 'B, T', id: 'sZYB5fFCiA4', d: 209 },
  Safehouse: { a: 'B', id: 'DJCjNBYwoNo', d: 163 },
  Ebay: { a: 'B, T, E', id: 'Nnwmc3k58Rw', d: 225 },
  Shadowface: { a: 'B, Bones', id: 'SlP5ILjf0UY', d: 215 },
  Spellbound: { a: 'B', id: 'Kp76OH12jcY', d: 205 },
  'Everlasting Flames': { a: 'B, T', id: 'fv_0cgtA3OM', d: 201 },
  Freeze: { a: 'B', id: 'fuC1jKU-wCw', d: 176 },
  'Upgrade Enabled': { a: 'B', id: 'YmaMerfPJng', d: 177 },
  Unreal: { a: 'B', id: 'QyX9Nymmtx0', d: 133 },
  Dragonfly: { a: 'B', id: 'TrRpnycSQoA', d: 143},
  'Blood Rain': { a: 'B, Y', id: 'RFcTac1ZUxY', d: 199 },
  'Into Dust': { a: 'B', id: 'TZnIoa4zNuw', d: 140},
  'Who Goes There': { a: 'B', id: '7gfItwH3LKQ', d: 189},
  'So What': { a: 'B, E', id: 'miMP5SQ_JQA', d: 199},
  Lovenote: { a: 'B', id: 'zCn_8eJ8x6M', d: 186},
  'Missing Person': { a: 'B', id: 'pQ2TmnjNCNg', d: 200},
  Romeo: { a: 'B', id: 'SzdoeUCM2HU', d: 171 },
  'Xd Out': { a: 'B', id: 'WH6o7diTHSs', d: 217 },
  Sick: { a: 'B', id: 'zN8I_ziciHw', d: 180 },
  Rip: { a: 'B', id: '8ww_eYCuIS8', d: 175 },
  'Bloodveil/Stillborn': { a: 'B, E', id: 'JN6sfZJZYsk', d: 210 },
  Sugar: { a: 'B', id: 'OqzBxiiR2QE', d: 186 },
  'Wrist Cry': { a: 'B', id: 'Ug3g3F9gwGM', d: 235 },
  Skin: { a: 'B', id: 'hOP_x9JK1', d: 216 },
  '7-Eleven': { a: 'B', id: 'ftUB2JvEImM', d: 164 },
  Butterfly: { a: 'B, T', id: '62tXF_7D0fs', d: 191 },
  MJ: { a: 'B, Y', id: '30dSFD6vqds', d: 245 },
  Psycho: { a: 'B, Adamn Killa', id: '18BeHal8hTs', d: 207 },
  '50SACINMYSOCIDGAF': { a: 'B, Y', id: 'C1L4KXgBAyo', d: 210 },
  'Destroy Me': { a: 'B', id: 'ithDuu8A680', d: 168 }
} as Record<string, { a: string; id: string; d: number }>
