export default {
  'Deletee (Intro)': { a: 'B, T', id: 'sZYB5fFCiA4', d: 209 },
  Safehouse: { a: 'B', id: 'DJCjNBYwoNo', d: 163 },
  Ebay: { a: 'B, T, E', id: 'Nnwmc3k58Rw', d: 225 },
  Shadowface: { a: 'B, Bones', id: 'SlP5ILjf0UY', d: 215 },
  Spellbound: { a: 'B', id: 'Kp76OH12jcY', d: 205 },
  'Everlasting Flames': { a: 'B, T', id: 'fv_0cgtA3OM', d: 201 },
  Freeze: { a: 'B', id: 'fuC1jKU-wCw', d: 176 },
  'Upgrade Enabled': { a: 'B', id: 'YmaMerfPJng', d: 177 },
  Unreal: { a: 'B', id: 'QyX9Nymmtx0', d: 133 },
  Dragonfly: { a: 'B', id: 'TrRpnycSQoA', d: 143 },
  'Blood Rain': { a: 'B, Y', id: 'RFcTac1ZUxY', d: 199 },
  'Into Dust': { a: 'B', id: 'TZnIoa4zNuw', d: 140 },
  'Who Goes There': { a: 'B', id: '7gfItwH3LKQ', d: 189 },
  'So What': { a: 'B, E', id: 'miMP5SQ_JQA', d: 199 },
  Lovenote: { a: 'B', id: 'zCn_8eJ8x6M', d: 186 },
  'Missing Person': { a: 'B', id: 'pQ2TmnjNCNg', d: 200 },
  Romeo: { a: 'B', id: 'SzdoeUCM2HU', d: 171 },
  'Xd Out': { a: 'B', id: 'WH6o7diTHSs', d: 217 },
  Sick: { a: 'B', id: 'zN8I_ziciHw', d: 180 },
  Rip: { a: 'B', id: '8ww_eYCuIS8', d: 175 },
  'Bloodveil/Stillborn': { a: 'B, E', id: 'JN6sfZJZYsk', d: 210 },
  Sugar: { a: 'B', id: 'OqzBxiiR2QE', d: 186 },
  'Wrist Cry': { a: 'B', id: 'Ug3g3F9gwGM', d: 235 },
  Skin: { a: 'B', id: 'hOP_x9JK1-g', d: 216 },
  '7-Eleven': { a: 'B', id: 'ftUB2JvEImM', d: 164 },
  Butterfly: { a: 'B, T', id: '62tXF_7D0fs', d: 191 },
  MJ: { a: 'B, Y', id: '30dSFD6vqds', d: 245 },
  Psycho: { a: 'B, Adamn Killa', id: '18BeHal8hTs', d: 207 },
  '50SACINMYSOCIDGAF': { a: 'B, Y', id: 'C1L4KXgBAyo', d: 210 },
  'Destroy Me': { a: 'B', id: 'ithDuu8A680', d: 168 },
  'AAA Powerline': { a: 'E', id: 'HeLdS491PDo', d: 256 },
  Peroxide: { a: 'E', id: 'toVvEuNRo3Y', d: 214 },
  Fragile: { a: 'E', id: 'fP7GD3F1euw', d: 173 },
  'Fruit Bleed Juice': { a: 'E', id: 'VBFJDYX8SPY', d: 72 },
  Cc: { a: 'E', id: 'hQNkd7pP_6A', d: 154 },
  Calcium: { a: 'E', id: '5XJLdu5qAhM', d: 224 },
  'Sugar & Diesel': { a: 'E', id: '4kswlS7SRsM', d: 199 },
  "Don't Ask": { a: 'E', id: 'rUoqWE429pg', d: 140 },
  Security: { a: 'E', id: 'Hv6kNL9vjj0', d: 155 },
  'Blue Eyes': { a: 'E', id: 'AbVrh0hUuQM', d: 93 },
  Time: { a: 'E', id: 'rKsb71ALRvo', d: 121 },
  'Legendary Member': { a: 'T, B, E, Y', id: 'WGr2QOy0ps8', d: 156 },
  SmartWater: { a: 'B', id: '4m0sVGVTTes', d: 150 },
  OKK: { a: 'B', id: 'D9QRWeiDxKI', d: 93 },
  'Mallwhore Freeestyle': { a: 'B', id: '8QUT4hpQbsw', d: 119 },
  'Be Nice 2 Me': { a: 'B', id: 'hJQjWKq7vrc', d: 127 },
  'Frosty the Snowman': { a: 'B', id: 'VOmLLsv2dDI', d: 170 },
  'Inside Out': { a: 'B, Y', id: 'ULUZ6dSHwbo', d: 137 },
  Close: { a: 'B', id: 'PCxgFp1H0Lk', d: 202 },
  Jaws: { a: 'B', id: 'kHbyCF35QNs', d: 116 },
  "Cartier'God Icedancer (Intermission)": { a: 'B', id: 'yGqgSa0y-dM', d: 181 },
  'Side by Side': { a: 'B, T', id: 'oF8r39I6vdA', d: 136 },
  Topman: { a: 'B', id: 'zeleydIQeM0', d: 193 },
  Waster: { a: 'B', id: 'CMrcYUxBAxc', d: 121 },
  'Special Place': { a: 'B', id: 'kuiB3xSaH8k', d: 122 },
  'Dg Jeans': { a: 'B', id: 'ONrNAX6j3vc', d: 103 },
  'Feel Like': { a: 'B', id: 'uDUCBwD7Hgs', d: 94 },
  Linkdin: { a: 'B', id: 'bnD2CWhspEM', d: 153 },
  'For Nothing': { a: 'B', id: '_eztqePWUwY', d: 120 },
  Anything: { a: 'B', id: 'pN72OsNCKNA', d: 157 },
  'The Silent Boy Cries (Ripsquadd Outro)': { a: 'B', id: 'fkijihXrdhs', d: 79 },
} as Record<string, { a: string; id: string; d: number }>
